baseURL = 'https://garrettsiegel.github.io/invoicecreator'
languageCode = 'en-us'
title = 'Invoice Template'
enableRobotsTXT = true

[security.exec]
  allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
  osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']